// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj3oLUX4fF88_UfPcESOyPxPJP5xeUpiw',
    appId: '1:814171235287:web:87321f531200dc05bd6192',
    messagingSenderId: '814171235287',
    projectId: 'sdotist',
    authDomain: 'sdotist.firebaseapp.com',
    storageBucket: 'sdotist.firebasestorage.app',
    measurementId: 'G-JBHL98QC4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15ppQM2hWrkymqNIHlx2ij119W95Slms',
    appId: '1:814171235287:android:bef7d1f08c3f4fabbd6192',
    messagingSenderId: '814171235287',
    projectId: 'sdotist',
    storageBucket: 'sdotist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4jBfUH3t4jYsQflnGyceKBsXcj5gzUA',
    appId: '1:814171235287:ios:705c39151ff314bebd6192',
    messagingSenderId: '814171235287',
    projectId: 'sdotist',
    storageBucket: 'sdotist.firebasestorage.app',
    iosBundleId: 'com.sdotist.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4jBfUH3t4jYsQflnGyceKBsXcj5gzUA',
    appId: '1:814171235287:ios:cf8d184c5925c5cabd6192',
    messagingSenderId: '814171235287',
    projectId: 'sdotist',
    storageBucket: 'sdotist.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj3oLUX4fF88_UfPcESOyPxPJP5xeUpiw',
    appId: '1:814171235287:web:cf169e0a55016c6abd6192',
    messagingSenderId: '814171235287',
    projectId: 'sdotist',
    authDomain: 'sdotist.firebaseapp.com',
    storageBucket: 'sdotist.firebasestorage.app',
    measurementId: 'G-C514KBHDJK',
  );
}
